
server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://103.218.122.180/demo_crud
    username: trandat
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update

  task:
    scheduling:
      enabled: 'false'