
server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_crud
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update

  task:
    scheduling:
      enabled: 'true'